omer.faruk/EI-966-Add_VNET_Integration_FA_Module
hmcts/cpp-terraform-functionapp-deployment pull request #36
Opened 2023-01-05 11:18 UTC by omerf-hmcts

omer.faruk/EI-966-Add_VNET_Integration_FA_Module

2023-01-06 11:23 UTC, varunvijayagopal requested changes

2023-01-06 11:23 UTC, varunvijayagopal commented on variables.tf
> +variable "revision" {
why do we need this ?

2023-01-06 11:23 UTC, varunvijayagopal commented on vars/dev/notifyatt.tfvars
> +revision          = "-01"
don't think we need this

2023-01-13 15:51 UTC, omerf-hmcts commented on vars/dev/notifyatt.tfvars
> +revision          = "-01"
this is removed

2023-01-16 14:12 UTC, akozichev-hmcts approved these changes

2023-01-16 15:11 UTC, omerf-hmcts commented
* Add Vnet Subnet Integration

2023-01-16 15:11 UTC, merged